const orders = require('./orders/orders.service.js');
const unit = require('./unit/unit.service.js');
const subunit = require('./subunit/subunit.service.js');
const accidentCauses = require('./accident-causes/accident-causes.service.js');
const accidents = require('./accidents/accidents.service.js');
const foremans = require('./foremans/foremans.service.js');
const goals = require('./goals/goals.service.js');
const machineGroups = require('./machine-groups/machine-groups.service.js');
const machines = require('./machines/machines.service.js');
const staff = require('./staff/staff.service.js');
const parts = require('./parts/parts.service.js');
const attachments = require('./attachments/attachments.service.js');
const categories = require('./categories/categories.service.js');
const operations = require('./operations/operations.service.js');
const users = require('./users/users.service.js');
const settings = require('./settings/settings.service.js');
const allowedSettingsValue = require('./allowed-settings-value/allowed-settings-value.service.js');
const userSettings = require('./user-settings/user-settings.service.js');
const roles = require('./roles/roles.service.js');
const uploads = require('./uploads/uploads.service.js');
const attachmentsUploads = require('./attachments-uploads/attachments-uploads.service.js');
const machineCategories = require('./machine-categories/machine-categories.service.js');
const operationMachines = require('./operation-machines/operation-machines.service.js');
const notices = require('./notices/notices.service.js');
const groupsStatic = require('./groups-static/groups-static.service.js');
const productionDataStatic = require('./production-data-static/production-data-static.service.js');
const uploadExcel = require('./upload-excel/upload-excel.service.js');
const ordersUploads = require('./orders-uploads/orders-uploads.service.js');
const machineGroupsGroups = require('./machine-groups-groups/machine-groups-groups.service.js');
const machineConditions = require('./machine-conditions/machine-conditions.service.js');
const conditions = require('./conditions/conditions.service.js');
const noticeTypes = require('./notice-types/notice-types.service.js');
const noticesUploads = require('./notices-uploads/notices-uploads.service.js');
const mailer = require('./mailer/mailer.service.js');
const authManagment = require('./auth-managment/auth-managment.service.js');
const keywords = require('./keywords/keywords.service.js');
const noticesKeywords = require('./notices-keywords/notices-keywords.service.js');
const planning = require('./planning/planning.service.js');
const workerDistribution = require('./worker-distribution/worker-distribution.service.js');
const events = require('./events/events.service.js');
const subcategories = require('./subcategories/subcategories.service.js');
const documents = require('./documents/documents.service.js');
const documentsUploads = require('./documents-uploads/documents-uploads.service.js');
const workerDistributionTemplate = require('./worker-distribution-template/worker-distribution-template.service.js');
const mdocsDocumentation = require('./mdocs-documentation/mdocs-documentation.service.js');
const digitalization = require('./digitalization/digitalization.service.js');
const digitalizationUploads = require('./digitalization-uploads/digitalization-uploads.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(orders);
  app.configure(unit);
  app.configure(subunit);
  app.configure(accidentCauses);
  app.configure(accidents);
  app.configure(foremans);
  app.configure(goals);
  app.configure(machineGroups);
  app.configure(machines);
  app.configure(staff);
  app.configure(parts);
  app.configure(attachments);
  app.configure(categories);
  app.configure(operations);
  app.configure(users);
  app.configure(settings);
  app.configure(allowedSettingsValue);
  app.configure(userSettings);
  app.configure(roles);
  app.configure(uploads);
  app.configure(attachmentsUploads);
  app.configure(machineCategories);
  app.configure(operationMachines);
  app.configure(notices);
  app.configure(groupsStatic);
  app.configure(productionDataStatic);
  app.configure(uploadExcel);
  app.configure(ordersUploads);
  app.configure(machineGroupsGroups);
  app.configure(machineConditions);
  app.configure(conditions);
  app.configure(noticeTypes);
  app.configure(noticesUploads);
  app.configure(mailer);
  app.configure(authManagment);
  app.configure(keywords);
  app.configure(noticesKeywords);
  app.configure(planning);
  app.configure(workerDistribution);
  app.configure(events);
  app.configure(subcategories);
  app.configure(documents);
  app.configure(documentsUploads);
  app.configure(documentsUploads);
  app.configure(workerDistributionTemplate);
  app.configure(mdocsDocumentation);
  app.configure(digitalization);
  app.configure(digitalizationUploads);
};
